# build with the following command
# sudo docker build -f Dockerfile_jupyter -t paramak_jupyter .

# run with the following command
# docker run -p 8888:8888 paramak_jupyter

# test with the folowing command
# sudo docker run --rm paramak_jupyter pytest ../tests

FROM jupyter/minimal-notebook

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

USER root

RUN apt-get --yes update
RUN apt-get install --yes libgl1-mesa-glx

RUN conda install -c cadquery -c conda-forge cadquery=2

# USER cq

# Copy over the source code
COPY paramak paramak/
COPY setup.py setup.py
COPY README.md README.md

RUN pip install .
# additional neutronics features avaialbe with pip install .[neutronics]

# Copy over the test folder
COPY tests tests/

WORKDIR paramak/examples

CMD ["/bin/bash"]
