name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - Pillow
  - cadquery=2
  - openmc
  - pip:
    - neutronics-material-maker
    - sympy
    - plasmaboundaries