name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - Pillow
  - cadquery=2.1
  - openmc
  - python=3.8
  - pip:
    - neutronics-material-maker
    - sympy
    - plasmaboundaries
    - sphinx-autodoc-typehints
    - defusedxml
    