
name: CI
on:  
  pull_request:    
    branches:
    - develop  
    - main
jobs:  
  build:     
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
      cadquery-version: [2.1, master]
    
   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker - Cadquery Version ${{ matrix.cadquery-version }}
     run: |
       docker build -t paramak --build-arg include_neutronics=true --build-arg cq_version=${{ matrix.cadquery-version}} --build-arg compile_cores=2 .
       docker run --rm paramak  /bin/bash -c "bash run_tests.sh && curl -s https://codecov.io/bash | bash"
