name: CI
on:  
  pull_request:    
    branches:
    - develop  
    - main
jobs:  
  build:     
   runs-on: ubuntu-latest

   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build -t paramak --build-arg include_neutronics=true --build-arg cq_version=master .
       docker run --rm paramak  /bin/bash -c "pytest /tests -v --cov=paramak --cov-append --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml && curl -s https://codecov.io/bash | bash"
